title: Marcus Unmasked
author:
  name: Marcus Helvig
  email: blog@marcus.helvig.net

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A place on the web to allow me to work through my thoughts by writing them down. This is a place that lets me unmask, and
  post without needing to act as if I'm a neurotypical person.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcus.helvig.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima-custom

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - _pages/uses.md
  - _pages/now.md
  - _pages/about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima-custom:
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  social_links:
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: github,         user_url: "https://github.com/MarcusP-P" }
    - { platform: keybase,        user_url: "https://keybase.io/marcusp" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: mastodon,        user_url: "https://mastodon.social/@MarcusP" }


