title: Marcus Unmasked
author:
  name: Marcus Helvig
  email: blog@marcus.helvig.net

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A site of geekery, neurodiversity, and whatever I think is interesting.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcus.helvig.net" # the base hostname & protocol for your site, e.g. http://example.com

timezone: Australia/Melbourne

# If you clone the Minima repo and build locally, use this setting.
theme: minima-custom

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

collections:
  pages:
    output: true

minimum_update: 2024-01-22T20:09:00+11:00

exclude:
  - theme/

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - _pages/uses.md
  - _pages/now.md
  - _pages/about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima-custom:

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"
  #date_format: "%A %e %B %y %l:%M %p"
  date_format: "%A %e %B %y %l:%M %p"

  # Generate social links in footer.
  social_links:
    -
      platform: mastodon
      title: Mastodon
      user_url: "https://mastodon.social/@MarcusP"
    - 
      platform: github
      title: GitHub
      user_url: "https://github.com/MarcusP-P" 
    - 
      platform: keybase
      title: Keybase
      user_url: "https://keybase.io/marcusp"
    - 
      platform: rss
      title: RSS Feed
      user_url: "/feed.xml"

# Serch engine verifications
webmaster_verifications:
  google: oQ1SNvLLThKyzprtyxtq6Ln0rpyB3zpWw-maES3TiPM
  bing: 6822EEAA21427BC40902F9A9FD16EC9E

# Google Analytics
google_analytics: G-M6DYHM029B