title: Marcus Unmasked
author:
  name: Marcus Helvig
  email: blog@marcus.helvig.net

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Neurodiverse people mask in public; they hide their true nature and act in ways that they think neurotypicals expect us to act.
  Unmasking is the act of dropping these pretences, and acting as we would act, without needing to fake it. This is my little 
  corner of the web, where I can be free to not mask. If you are offended or upset by soemthing I've said, remember that you could
  have taken soemthing in a way in which it wasn't meant to be. The onus is on you to talk to me about it, otherwise I'll assume
  it's all good.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcus.helvig.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima-custom

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - _pages/uses.md
  - _pages/now.md
  - _pages/about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima-custom:
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  #social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }


